#propiedades del keystore del servicio web
JPS_PATH=/u01/oracle/config/BPM/domains/ANM_DEV_SOA_DOMAIN/servers/AdminServer/upload/WCCWebServices/app/jps-config.xml
KEYSTORE_PATH=/u01/oracle/config/BPM/domains/ANM_DEV_SOA_DOMAIN/servers/AdminServer/upload/WCCWebServices/app/default-keystore.jks
KEYSTORE_PASSWORD=welcome1
KEY_ALIAS=orakey
KEY_PASSWORD=welcome1

#Url de conexi�n a WebCenter Content con Idc
URL_IDC=http://10.0.100.251:8103/cs/idcplg

#propiedades del servicio web de WebCenter Content
URL_WSDL_GENERIC=http://10.0.100.251:8103/idcws/GenericSoapPort?wsdl
WCC_CONN_TIMEOUT=3000
WCC_READ_TIMEOUT=10000

#propiedades del servicio web de CMC
URL_WS_CMC=http://esmeraldarmnpru.anm.local:9090/ServiciosIntegracionSGD/services/IntegracionSGDCMC?wsdl
CMC_CONN_TIMEOUT=3000
CMC_READ_TIMEOUT=4000
CMC_WS_USER=gmrojas

#propiedades usuario content
WCC_USER=bpmuser
WCC_PASSWORD=*BPM_wcc0nt3nt*

#path de plantillas
PATH_PLANTILLAS=/Enterprise Libraries/SGD/PLANTILLAS

#rutas de las series de expedientes mineros
PATH_TITULOS_MINEROS=/Enterprise Libraries/ANM/CP2-MISIONAL/PR5-GENERACION DE TITULOS MINEROS/SD68-TITULOS MINEROS
PATH_SOLICITUDES_MINERAS=/Enterprise Libraries/ANM/CP2-MISIONAL/PR5-GENERACION DE TITULOS MINEROS/SD65-SOLICITUDES MINERAS
PATH_SS_PIN=/Enterprise Libraries/ANM/CP2-MISIONAL/PR5-GENERACION DE TITULOS MINEROS/SD65-SOLICITUDES MINERAS/SS68.10-TITULO DE PROYECTO DE INTERES NACIONAL
PATH_CONS_COM=/Enterprise Libraries/ANM/CP3-APOYO/PR16-GESTION DOCUMENTAL/SD16-CONSECUTIVO COMUNICACIONES OFICIALES
PATH_PQRS=/Enterprise Libraries/ANM/CP2-MISIONAL/PR9-ATENCION INTEGRAL Y SERVICIOS A GRUPOS DE INTERES/SD47-DERECHOS DE PETICION QUEJAS RECLAMOS Y SUGERENCIAS

#series
SERIE_CONS_COM=SD16-CONSECUTIVO COMUNICACIONES OFICIALES

#subseries
TITULO_PIN=SS68.10-TITULO DE PROYECTO DE INTERES NACIONAL

#par�metros a validar por servicio
PARAM_CARGAR_DOC=dSecurityGroup;dDocType;dDocTitle;fFolderName;primaryFile;xANM_Tramite;xANM_Tipo_Documental;xANM_Referencia;xANM_UnidadAdministrativa
PARAM_CREAR_SOLICITUD=dSecurityGroup;dDocAccount;dDocType;dDocTitle;fFolderName;primaryFile;xANM_Tramite;xANM_Tipo_Documental;xANM_Referencia;xANM_UnidadAdministrativa;origenSolicitud
PARAM_CREAR_TITULO=fFolderName;xANM_Referencia
PARAM_RECHAZAR_SOLICITUD=xANM_Referencia
PARAM_DESCARGAR_DOC=dDocName;dID

#listas de cuadernos de expedientes mineros
CUADERNOS_TITULO_MINERO=CD01-PRINCIPAL;CD02-CONTRACTUAL;CD03-POLIZA;CD04-TECNICO;CD05-AMBIENTAL;CD05-SOCIAL;CD06-ECONOMICO;CD07-FBM;CD08-AMPARO ADMINISTRATIVO;CD09-GESTION JURIDICA
CUADERNOS_TITULO_PIN=CD01-PRINCIPAL;CD02-CONTRACTUAL;CD03-POLIZA;CD04-TECNICO;CD05-AMBIENTAL;CD05-SOCIAL;CD06-ECONOMICO;CD07-FBM;CD08-AMPARO ADMINISTRATIVO;CD09-GESTION JURIDICA

#propiedades de los sistemas de ANM
SISTEMAS_ANM=CMC|0;FISCAMINERO|1;WEBSAFI|2;RADICADOR_WEB|3;TR_LINEA|4

#propiedades para el archivo ODT
nroRadicado=<<NumRadicado>>
asunto=<<Asunto>>
nroFolios=<<NumFolios>>
referencia=<<Referencia>>
esTituloMinero=<<TituloMinero>>
nroPlaca=<<NumPlaca>>
nroRadicadoRelacionado=<<NumRadicadoRelacionado>>
requiereRespuesta=<<RequiereRespuesta>>
nroAnexos=<<NumAnexos>>
fechaRadicado=<<fechaRadicado>>
dependenciaDestino=<<DependenciaDestino>>
destinatarioInterno=<<DestintarioInterno>>
tipoComunicacion=<<TipoComunicacion>
tiempoRespuesta=<<TiempoRespuesta>>
fechaCreacion=<<FechaCreacion>>
medioEnvio=<<MedioEnvio>>
dependenciaOrigen=<<DependenciaOrigen>>
codigoBarras=<<CodigoBarras>>
elaboro=<<Elaboro>>
tipoPqrs=<<TipoPqrs>>
tipoIdentificacionInteresado=<<TipoIdentificacionInteresado>>
numIdentificacionInteresado=<<NumIdentificacionInteresado>>
nombreCompletoInteresado=<<NombreCompletoInteresado>>
emailInteresado=<<EmailInteresado>>
telefonoInteresado=<<TelefonoInteresado>>
celularInteresado=<<CelularInteresado>>
direccionInteresado=<<DireccionInteresado>>
paisInteresado=<<PaisInteresado>>
departamentoInteresado=<<DepartamentoInteresado>>
municipioInteresado=<<MunicipioInteresado>>

#Propiedades de host para descarga de documentos (VirtualDirectory de WL)
virtual.directory.path.http=http://wcdev.anm.local/sgd.admin/
virtual.directory.path=/ftp/comunicaciones/

libre.office.path=/Applications/OpenOffice.org.app/Contents/

#Propiedades Mail Service
mail.smtp.auth=false
mail.smtp.starttls.enable=false
mail.smtp.host=smtp.anm.gov.co
mail.smtp.port=25

#Cuenta Mail
mail.account.username=rucompru@anm.gov.co
mail.account.password=Anmrucom
