package co.gov.anm.sgd.bc.model.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 21 07:56:16 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SGDRolesUsuarioViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdUsuario {
            protected Object get(SGDRolesUsuarioViewRowImpl obj) {
                return obj.getIdUsuario();
            }

            protected void put(SGDRolesUsuarioViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NombreUsuario {
            protected Object get(SGDRolesUsuarioViewRowImpl obj) {
                return obj.getNombreUsuario();
            }

            protected void put(SGDRolesUsuarioViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CodigoDependencia {
            protected Object get(SGDRolesUsuarioViewRowImpl obj) {
                return obj.getCodigoDependencia();
            }

            protected void put(SGDRolesUsuarioViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Email {
            protected Object get(SGDRolesUsuarioViewRowImpl obj) {
                return obj.getEmail();
            }

            protected void put(SGDRolesUsuarioViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IdRol {
            protected Object get(SGDRolesUsuarioViewRowImpl obj) {
                return obj.getIdRol();
            }

            protected void put(SGDRolesUsuarioViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NombreRol {
            protected Object get(SGDRolesUsuarioViewRowImpl obj) {
                return obj.getNombreRol();
            }

            protected void put(SGDRolesUsuarioViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(SGDRolesUsuarioViewRowImpl object);

        protected abstract void put(SGDRolesUsuarioViewRowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDUSUARIO = AttributesEnum.IdUsuario.index();
    public static final int NOMBREUSUARIO = AttributesEnum.NombreUsuario.index();
    public static final int CODIGODEPENDENCIA = AttributesEnum.CodigoDependencia.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int IDROL = AttributesEnum.IdRol.index();
    public static final int NOMBREROL = AttributesEnum.NombreRol.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SGDRolesUsuarioViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IdUsuario.
     * @return the IdUsuario
     */
    public String getIdUsuario() {
        return (String) getAttributeInternal(IDUSUARIO);
    }

    /**
     * Gets the attribute value for the calculated attribute NombreUsuario.
     * @return the NombreUsuario
     */
    public String getNombreUsuario() {
        return (String) getAttributeInternal(NOMBREUSUARIO);
    }

    /**
     * Gets the attribute value for the calculated attribute CodigoDependencia.
     * @return the CodigoDependencia
     */
    public Number getCodigoDependencia() {
        return (Number) getAttributeInternal(CODIGODEPENDENCIA);
    }

    /**
     * Gets the attribute value for the calculated attribute Email.
     * @return the Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Gets the attribute value for the calculated attribute IdRol.
     * @return the IdRol
     */
    public Number getIdRol() {
        return (Number) getAttributeInternal(IDROL);
    }

    /**
     * Gets the attribute value for the calculated attribute NombreRol.
     * @return the NombreRol
     */
    public String getNombreRol() {
        return (String) getAttributeInternal(NOMBREROL);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

