package co.gov.anm.sgd.bc.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 19 17:22:53 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SGDUsuarioRolViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SGDUsuarioRolViewImpl() {
    }
}

