package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 13 09:18:03 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AnmTipoDocumentalVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AnmTipoDocumentalVOImpl() {
    }
}

