package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 16:40:18 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FldCuadernoVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FldCuadernoVOImpl() {
    }

    /**
     * Returns the bind variable value for subSerieIdSel.
     * @return bind variable value for subSerieIdSel
     */
    public String getsubSerieIdSel() {
        return (String) getNamedWhereClauseParam("subSerieIdSel");
    }

    /**
     * Sets <code>value</code> for bind variable subSerieIdSel.
     * @param value value to bind as subSerieIdSel
     */
    public void setsubSerieIdSel(String value) {
        setNamedWhereClauseParam("subSerieIdSel", value);
    }
}

