package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 16:40:30 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FldProcesoAdmVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FldProcesoAdmVOImpl() {
    }

    /**
     * Returns the bind variable value for tpProcesoAdmSel.
     * @return bind variable value for tpProcesoAdmSel
     */
    public String gettpProcesoAdmSel() {
        return (String) getNamedWhereClauseParam("tpProcesoAdmSel");
    }

    /**
     * Sets <code>value</code> for bind variable tpProcesoAdmSel.
     * @param value value to bind as tpProcesoAdmSel
     */
    public void settpProcesoAdmSel(String value) {
        setNamedWhereClauseParam("tpProcesoAdmSel", value);
    }
}

