package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 16:40:43 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FldSerieVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FldSerieVOImpl() {
    }

    /**
     * Returns the bind variable value for procesoAdmSel.
     * @return bind variable value for procesoAdmSel
     */
    public String getprocesoAdmSel() {
        return (String) getNamedWhereClauseParam("procesoAdmSel");
    }

    /**
     * Sets <code>value</code> for bind variable procesoAdmSel.
     * @param value value to bind as procesoAdmSel
     */
    public void setprocesoAdmSel(String value) {
        setNamedWhereClauseParam("procesoAdmSel", value);
    }
}

