package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 16:41:05 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FldTipoProcAdmVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FldTipoProcAdmVOImpl() {
    }
}

