package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 27 10:06:39 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MedioEnvioVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MedioEnvioVOImpl() {
    }
}

