package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 28 16:45:59 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TipoIdentificacionVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TipoIdentificacionVOImpl() {
    }
}

