package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 18 16:19:56 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UsuarioVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UsuarioVOImpl() {
    }

    /**
     * Returns the variable value for codDependenciaSel.
     * @return variable value for codDependenciaSel
     */
    public Long getcodDependenciaSel() {
        return (Long) ensureVariableManager().getVariableValue("codDependenciaSel");
    }

    /**
     * Sets <code>value</code> for variable codDependenciaSel.
     * @param value value to bind as codDependenciaSel
     */
    public void setcodDependenciaSel(Long value) {
        ensureVariableManager().setVariableValue("codDependenciaSel", value);
    }
}

