package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 21 09:30:56 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AsignacionComunicacionVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AsignacionComunicacionVOImpl() {
    }
}

