package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 16:40:53 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FldSubSerieVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FldSubSerieVOImpl() {
    }

    /**
     * Returns the bind variable value for serieIdSel.
     * @return bind variable value for serieIdSel
     */
    public String getserieIdSel() {
        return (String) getNamedWhereClauseParam("serieIdSel");
    }

    /**
     * Sets <code>value</code> for bind variable serieIdSel.
     * @param value value to bind as serieIdSel
     */
    public void setserieIdSel(String value) {
        setNamedWhereClauseParam("serieIdSel", value);
    }
}

