package co.gov.anm.model.view;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 26 12:24:55 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TrueFalseVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        id,
        valor;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return co.gov
                     .anm
                     .model
                     .view
                     .TrueFalseVORowImpl
                     .AttributesEnum
                     .firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return co.gov
                     .anm
                     .model
                     .view
                     .TrueFalseVORowImpl
                     .AttributesEnum
                     .firstIndex() + co.gov
                                       .anm
                                       .model
                                       .view
                                       .TrueFalseVORowImpl
                                       .AttributesEnum
                                       .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = co.gov
                         .anm
                         .model
                         .view
                         .TrueFalseVORowImpl
                         .AttributesEnum
                         .values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.id.index();
    public static final int VALOR = AttributesEnum.valor.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TrueFalseVORowImpl() {
    }
}

