package co.gov.anm.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 26 12:24:55 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TrueFalseVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TrueFalseVOImpl() {
    }
}

