package co.gov.anm.sgd.bc.model.entities;

import java.sql.PreparedStatement;
import java.sql.ResultSet;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 02 18:47:29 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SGDComunicacionImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdComunicacion {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getIdComunicacion();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setIdComunicacion((Number) value);
            }
        }
        ,
        NroRadicado {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getNroRadicado();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setNroRadicado((String) value);
            }
        }
        ,
        Asunto {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getAsunto();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setAsunto((String) value);
            }
        }
        ,
        NroFolios {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getNroFolios();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setNroFolios((Number) value);
            }
        }
        ,
        Referencia {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getReferencia();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setReferencia((String) value);
            }
        }
        ,
        EsTitulo {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getEsTitulo();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setEsTitulo((String) value);
            }
        }
        ,
        NroPlaca {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getNroPlaca();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setNroPlaca((String) value);
            }
        }
        ,
        NroRadicadoRelacionado {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getNroRadicadoRelacionado();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setNroRadicadoRelacionado((String) value);
            }
        }
        ,
        RequiereRespuesta {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getRequiereRespuesta();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setRequiereRespuesta((String) value);
            }
        }
        ,
        NroAnexos {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getNroAnexos();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setNroAnexos((Number) value);
            }
        }
        ,
        IdUnidadProductora {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getIdUnidadProductora();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setIdUnidadProductora((Number) value);
            }
        }
        ,
        IdDependenciaDestino {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getIdDependenciaDestino();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setIdDependenciaDestino((Number) value);
            }
        }
        ,
        FechaCreacion {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getFechaCreacion();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setFechaCreacion((Date) value);
            }
        }
        ,
        FechaActualizacion {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getFechaActualizacion();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setFechaActualizacion((Date) value);
            }
        }
        ,
        UsuarioCreacion {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getUsuarioCreacion();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setUsuarioCreacion((String) value);
            }
        }
        ,
        UsuarioActualizacion {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getUsuarioActualizacion();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setUsuarioActualizacion((String) value);
            }
        }
        ,
        ContentFldComunicaciones {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getContentFldComunicaciones();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setContentFldComunicaciones((String) value);
            }
        }
        ,
        ContentFldTitulo {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getContentFldTitulo();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setContentFldTitulo((String) value);
            }
        }
        ,
        ContentFldOtro {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getContentFldOtro();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setContentFldOtro((String) value);
            }
        }
        ,
        GrupoSeguridad {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getGrupoSeguridad();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setGrupoSeguridad((String) value);
            }
        }
        ,
        IdTramite {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getIdTramite();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setIdTramite((Number) value);
            }
        }
        ,
        Tramite {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getTramite();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setTramite((String) value);
            }
        }
        ,
        IdTipoDocumentalTramite {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getIdTipoDocumentalTramite();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setIdTipoDocumentalTramite((Number) value);
            }
        }
        ,
        EstadoComunicacion {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getEstadoComunicacion();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setEstadoComunicacion((String) value);
            }
        }
        ,
        EsPqrs {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getEsPqrs();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setEsPqrs((String) value);
            }
        }
        ,
        IdentifReservada {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getIdentifReservada();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setIdentifReservada((String) value);
            }
        }
        ,
        TrasladoOtraEntidad {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getTrasladoOtraEntidad();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setTrasladoOtraEntidad((String) value);
            }
        }
        ,
        Comentarios {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getComentarios();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setComentarios((String) value);
            }
        }
        ,
        CodSerie {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getCodSerie();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setCodSerie((String) value);
            }
        }
        ,
        NombreSerie {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getNombreSerie();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setNombreSerie((String) value);
            }
        }
        ,
        AccesoNegado {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getAccesoNegado();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setAccesoNegado((String) value);
            }
        }
        ,
        CodSubserie {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getCodSubserie();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setCodSubserie((String) value);
            }
        }
        ,
        NombreSubserie {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getNombreSubserie();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setNombreSubserie((String) value);
            }
        }
        ,
        NombreTpDoc {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getNombreTpDoc();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setNombreTpDoc((String) value);
            }
        }
        ,
        DiasParaRespuesta {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getDiasParaRespuesta();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setDiasParaRespuesta((Number) value);
            }
        }
        ,
        FechaVencimiento {
            protected Object get(SGDComunicacionImpl obj) {
                return obj.getFechaVencimiento();
            }

            protected void put(SGDComunicacionImpl obj, Object value) {
                obj.setFechaVencimiento((Date) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(SGDComunicacionImpl object);

        protected abstract void put(SGDComunicacionImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDCOMUNICACION = AttributesEnum.IdComunicacion.index();
    public static final int NRORADICADO = AttributesEnum.NroRadicado.index();
    public static final int ASUNTO = AttributesEnum.Asunto.index();
    public static final int NROFOLIOS = AttributesEnum.NroFolios.index();
    public static final int REFERENCIA = AttributesEnum.Referencia.index();
    public static final int ESTITULO = AttributesEnum.EsTitulo.index();
    public static final int NROPLACA = AttributesEnum.NroPlaca.index();
    public static final int NRORADICADORELACIONADO = AttributesEnum.NroRadicadoRelacionado.index();
    public static final int REQUIERERESPUESTA = AttributesEnum.RequiereRespuesta.index();
    public static final int NROANEXOS = AttributesEnum.NroAnexos.index();
    public static final int IDUNIDADPRODUCTORA = AttributesEnum.IdUnidadProductora.index();
    public static final int IDDEPENDENCIADESTINO = AttributesEnum.IdDependenciaDestino.index();
    public static final int FECHACREACION = AttributesEnum.FechaCreacion.index();
    public static final int FECHAACTUALIZACION = AttributesEnum.FechaActualizacion.index();
    public static final int USUARIOCREACION = AttributesEnum.UsuarioCreacion.index();
    public static final int USUARIOACTUALIZACION = AttributesEnum.UsuarioActualizacion.index();
    public static final int CONTENTFLDCOMUNICACIONES = AttributesEnum.ContentFldComunicaciones.index();
    public static final int CONTENTFLDTITULO = AttributesEnum.ContentFldTitulo.index();
    public static final int CONTENTFLDOTRO = AttributesEnum.ContentFldOtro.index();
    public static final int GRUPOSEGURIDAD = AttributesEnum.GrupoSeguridad.index();
    public static final int IDTRAMITE = AttributesEnum.IdTramite.index();
    public static final int TRAMITE = AttributesEnum.Tramite.index();
    public static final int IDTIPODOCUMENTALTRAMITE = AttributesEnum.IdTipoDocumentalTramite.index();
    public static final int ESTADOCOMUNICACION = AttributesEnum.EstadoComunicacion.index();
    public static final int ESPQRS = AttributesEnum.EsPqrs.index();
    public static final int IDENTIFRESERVADA = AttributesEnum.IdentifReservada.index();
    public static final int TRASLADOOTRAENTIDAD = AttributesEnum.TrasladoOtraEntidad.index();
    public static final int COMENTARIOS = AttributesEnum.Comentarios.index();
    public static final int CODSERIE = AttributesEnum.CodSerie.index();
    public static final int NOMBRESERIE = AttributesEnum.NombreSerie.index();
    public static final int ACCESONEGADO = AttributesEnum.AccesoNegado.index();
    public static final int CODSUBSERIE = AttributesEnum.CodSubserie.index();
    public static final int NOMBRESUBSERIE = AttributesEnum.NombreSubserie.index();
    public static final int NOMBRETPDOC = AttributesEnum.NombreTpDoc.index();
    public static final int DIASPARARESPUESTA = AttributesEnum.DiasParaRespuesta.index();
    public static final int FECHAVENCIMIENTO = AttributesEnum.FechaVencimiento.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SGDComunicacionImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("co.gov.anm.sgd.bc.model.entities.SGDComunicacion");
    }


    /**
     * Gets the attribute value for IdComunicacion, using the alias name IdComunicacion.
     * @return the value of IdComunicacion
     */
    public Number getIdComunicacion() {
        return (Number) getAttributeInternal(IDCOMUNICACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdComunicacion.
     * @param value value to set the IdComunicacion
     */
    public void setIdComunicacion(Number value) {
        setAttributeInternal(IDCOMUNICACION, value);
    }

    /**
     * Gets the attribute value for NroRadicado, using the alias name NroRadicado.
     * @return the value of NroRadicado
     */
    public String getNroRadicado() {
        return (String) getAttributeInternal(NRORADICADO);
    }

    /**
     * Sets <code>value</code> as the attribute value for NroRadicado.
     * @param value value to set the NroRadicado
     */
    public void setNroRadicado(String value) {
        setAttributeInternal(NRORADICADO, value);
    }

    /**
     * Gets the attribute value for Asunto, using the alias name Asunto.
     * @return the value of Asunto
     */
    public String getAsunto() {
        return (String) getAttributeInternal(ASUNTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Asunto.
     * @param value value to set the Asunto
     */
    public void setAsunto(String value) {
        setAttributeInternal(ASUNTO, value);
    }

    /**
     * Gets the attribute value for NroFolios, using the alias name NroFolios.
     * @return the value of NroFolios
     */
    public Number getNroFolios() {
        return (Number) getAttributeInternal(NROFOLIOS);
    }

    /**
     * Sets <code>value</code> as the attribute value for NroFolios.
     * @param value value to set the NroFolios
     */
    public void setNroFolios(Number value) {
        setAttributeInternal(NROFOLIOS, value);
    }

    /**
     * Gets the attribute value for Referencia, using the alias name Referencia.
     * @return the value of Referencia
     */
    public String getReferencia() {
        return (String) getAttributeInternal(REFERENCIA);
    }

    /**
     * Sets <code>value</code> as the attribute value for Referencia.
     * @param value value to set the Referencia
     */
    public void setReferencia(String value) {
        setAttributeInternal(REFERENCIA, value);
    }

    /**
     * Gets the attribute value for EsTitulo, using the alias name EsTitulo.
     * @return the value of EsTitulo
     */
    public String getEsTitulo() {
        return (String) getAttributeInternal(ESTITULO);
    }

    /**
     * Sets <code>value</code> as the attribute value for EsTitulo.
     * @param value value to set the EsTitulo
     */
    public void setEsTitulo(String value) {
        setAttributeInternal(ESTITULO, value);
    }

    /**
     * Gets the attribute value for NroPlaca, using the alias name NroPlaca.
     * @return the value of NroPlaca
     */
    public String getNroPlaca() {
        return (String) getAttributeInternal(NROPLACA);
    }

    /**
     * Sets <code>value</code> as the attribute value for NroPlaca.
     * @param value value to set the NroPlaca
     */
    public void setNroPlaca(String value) {
        setAttributeInternal(NROPLACA, value);
    }

    /**
     * Gets the attribute value for NroRadicadoRelacionado, using the alias name NroRadicadoRelacionado.
     * @return the value of NroRadicadoRelacionado
     */
    public String getNroRadicadoRelacionado() {
        return (String) getAttributeInternal(NRORADICADORELACIONADO);
    }

    /**
     * Sets <code>value</code> as the attribute value for NroRadicadoRelacionado.
     * @param value value to set the NroRadicadoRelacionado
     */
    public void setNroRadicadoRelacionado(String value) {
        setAttributeInternal(NRORADICADORELACIONADO, value);
    }

    /**
     * Gets the attribute value for RequiereRespuesta, using the alias name RequiereRespuesta.
     * @return the value of RequiereRespuesta
     */
    public String getRequiereRespuesta() {
        return (String) getAttributeInternal(REQUIERERESPUESTA);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequiereRespuesta.
     * @param value value to set the RequiereRespuesta
     */
    public void setRequiereRespuesta(String value) {
        setAttributeInternal(REQUIERERESPUESTA, value);
    }

    /**
     * Gets the attribute value for NroAnexos, using the alias name NroAnexos.
     * @return the value of NroAnexos
     */
    public Number getNroAnexos() {
        return (Number) getAttributeInternal(NROANEXOS);
    }

    /**
     * Sets <code>value</code> as the attribute value for NroAnexos.
     * @param value value to set the NroAnexos
     */
    public void setNroAnexos(Number value) {
        setAttributeInternal(NROANEXOS, value);
    }

    /**
     * Gets the attribute value for IdUnidadProductora, using the alias name IdUnidadProductora.
     * @return the value of IdUnidadProductora
     */
    public Number getIdUnidadProductora() {
        return (Number) getAttributeInternal(IDUNIDADPRODUCTORA);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdUnidadProductora.
     * @param value value to set the IdUnidadProductora
     */
    public void setIdUnidadProductora(Number value) {
        setAttributeInternal(IDUNIDADPRODUCTORA, value);
    }

    /**
     * Gets the attribute value for IdDependenciaDestino, using the alias name IdDependenciaDestino.
     * @return the value of IdDependenciaDestino
     */
    public Number getIdDependenciaDestino() {
        return (Number) getAttributeInternal(IDDEPENDENCIADESTINO);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdDependenciaDestino.
     * @param value value to set the IdDependenciaDestino
     */
    public void setIdDependenciaDestino(Number value) {
        setAttributeInternal(IDDEPENDENCIADESTINO, value);
    }

    /**
     * Gets the attribute value for FechaCreacion, using the alias name FechaCreacion.
     * @return the value of FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date) getAttributeInternal(FECHACREACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaCreacion.
     * @param value value to set the FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**
     * Gets the attribute value for FechaActualizacion, using the alias name FechaActualizacion.
     * @return the value of FechaActualizacion
     */
    public Date getFechaActualizacion() {
        return (Date) getAttributeInternal(FECHAACTUALIZACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaActualizacion.
     * @param value value to set the FechaActualizacion
     */
    public void setFechaActualizacion(Date value) {
        setAttributeInternal(FECHAACTUALIZACION, value);
    }

    /**
     * Gets the attribute value for UsuarioCreacion, using the alias name UsuarioCreacion.
     * @return the value of UsuarioCreacion
     */
    public String getUsuarioCreacion() {
        return (String) getAttributeInternal(USUARIOCREACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsuarioCreacion.
     * @param value value to set the UsuarioCreacion
     */
    public void setUsuarioCreacion(String value) {
        setAttributeInternal(USUARIOCREACION, value);
    }

    /**
     * Gets the attribute value for UsuarioActualizacion, using the alias name UsuarioActualizacion.
     * @return the value of UsuarioActualizacion
     */
    public String getUsuarioActualizacion() {
        return (String) getAttributeInternal(USUARIOACTUALIZACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsuarioActualizacion.
     * @param value value to set the UsuarioActualizacion
     */
    public void setUsuarioActualizacion(String value) {
        setAttributeInternal(USUARIOACTUALIZACION, value);
    }

    /**
     * Gets the attribute value for ContentFldComunicaciones, using the alias name ContentFldComunicaciones.
     * @return the value of ContentFldComunicaciones
     */
    public String getContentFldComunicaciones() {
        return (String) getAttributeInternal(CONTENTFLDCOMUNICACIONES);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContentFldComunicaciones.
     * @param value value to set the ContentFldComunicaciones
     */
    public void setContentFldComunicaciones(String value) {
        setAttributeInternal(CONTENTFLDCOMUNICACIONES, value);
    }

    /**
     * Gets the attribute value for ContentFldTitulo, using the alias name ContentFldTitulo.
     * @return the value of ContentFldTitulo
     */
    public String getContentFldTitulo() {
        return (String) getAttributeInternal(CONTENTFLDTITULO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContentFldTitulo.
     * @param value value to set the ContentFldTitulo
     */
    public void setContentFldTitulo(String value) {
        setAttributeInternal(CONTENTFLDTITULO, value);
    }

    /**
     * Gets the attribute value for ContentFldOtro, using the alias name ContentFldOtro.
     * @return the value of ContentFldOtro
     */
    public String getContentFldOtro() {
        return (String) getAttributeInternal(CONTENTFLDOTRO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContentFldOtro.
     * @param value value to set the ContentFldOtro
     */
    public void setContentFldOtro(String value) {
        setAttributeInternal(CONTENTFLDOTRO, value);
    }

    /**
     * Gets the attribute value for GrupoSeguridad, using the alias name GrupoSeguridad.
     * @return the value of GrupoSeguridad
     */
    public String getGrupoSeguridad() {
        return (String) getAttributeInternal(GRUPOSEGURIDAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrupoSeguridad.
     * @param value value to set the GrupoSeguridad
     */
    public void setGrupoSeguridad(String value) {
        setAttributeInternal(GRUPOSEGURIDAD, value);
    }

    /**
     * Gets the attribute value for IdTramite, using the alias name IdTramite.
     * @return the value of IdTramite
     */
    public Number getIdTramite() {
        return (Number) getAttributeInternal(IDTRAMITE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdTramite.
     * @param value value to set the IdTramite
     */
    public void setIdTramite(Number value) {
        setAttributeInternal(IDTRAMITE, value);
    }

    /**
     * Gets the attribute value for Tramite, using the alias name Tramite.
     * @return the value of Tramite
     */
    public String getTramite() {
        return (String) getAttributeInternal(TRAMITE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Tramite.
     * @param value value to set the Tramite
     */
    public void setTramite(String value) {
        setAttributeInternal(TRAMITE, value);
    }

    /**
     * Gets the attribute value for IdTipoDocumentalTramite, using the alias name IdTipoDocumentalTramite.
     * @return the value of IdTipoDocumentalTramite
     */
    public Number getIdTipoDocumentalTramite() {
        return (Number) getAttributeInternal(IDTIPODOCUMENTALTRAMITE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdTipoDocumentalTramite.
     * @param value value to set the IdTipoDocumentalTramite
     */
    public void setIdTipoDocumentalTramite(Number value) {
        setAttributeInternal(IDTIPODOCUMENTALTRAMITE, value);
    }

    /**
     * Gets the attribute value for EstadoComunicacion, using the alias name EstadoComunicacion.
     * @return the value of EstadoComunicacion
     */
    public String getEstadoComunicacion() {
        return (String) getAttributeInternal(ESTADOCOMUNICACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for EstadoComunicacion.
     * @param value value to set the EstadoComunicacion
     */
    public void setEstadoComunicacion(String value) {
        setAttributeInternal(ESTADOCOMUNICACION, value);
    }

    /**
     * Gets the attribute value for EsPqrs, using the alias name EsPqrs.
     * @return the value of EsPqrs
     */
    public String getEsPqrs() {
        return (String) getAttributeInternal(ESPQRS);
    }

    /**
     * Sets <code>value</code> as the attribute value for EsPqrs.
     * @param value value to set the EsPqrs
     */
    public void setEsPqrs(String value) {
        setAttributeInternal(ESPQRS, value);
    }

    /**
     * Gets the attribute value for IdentifReservada, using the alias name IdentifReservada.
     * @return the value of IdentifReservada
     */
    public String getIdentifReservada() {
        return (String) getAttributeInternal(IDENTIFRESERVADA);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdentifReservada.
     * @param value value to set the IdentifReservada
     */
    public void setIdentifReservada(String value) {
        setAttributeInternal(IDENTIFRESERVADA, value);
    }

    /**
     * Gets the attribute value for TrasladoOtraEntidad, using the alias name TrasladoOtraEntidad.
     * @return the value of TrasladoOtraEntidad
     */
    public String getTrasladoOtraEntidad() {
        return (String) getAttributeInternal(TRASLADOOTRAENTIDAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrasladoOtraEntidad.
     * @param value value to set the TrasladoOtraEntidad
     */
    public void setTrasladoOtraEntidad(String value) {
        setAttributeInternal(TRASLADOOTRAENTIDAD, value);
    }

    /**
     * Gets the attribute value for AccesoNegado, using the alias name AccesoNegado.
     * @return the value of AccesoNegado
     */
    public String getAccesoNegado() {
        return (String) getAttributeInternal(ACCESONEGADO);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccesoNegado.
     * @param value value to set the AccesoNegado
     */
    public void setAccesoNegado(String value) {
        setAttributeInternal(ACCESONEGADO, value);
    }

    /**
     * Gets the attribute value for CodSerie, using the alias name CodSerie.
     * @return the value of CodSerie
     */
    public String getCodSerie() {
        return (String) getAttributeInternal(CODSERIE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CodSerie.
     * @param value value to set the CodSerie
     */
    public void setCodSerie(String value) {
        setAttributeInternal(CODSERIE, value);
    }

    /**
     * Gets the attribute value for CodSubserie, using the alias name CodSubserie.
     * @return the value of CodSubserie
     */
    public String getCodSubserie() {
        return (String) getAttributeInternal(CODSUBSERIE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CodSubserie.
     * @param value value to set the CodSubserie
     */
    public void setCodSubserie(String value) {
        setAttributeInternal(CODSUBSERIE, value);
    }

    /**
     * Gets the attribute value for Comentarios, using the alias name Comentarios.
     * @return the value of Comentarios
     */
    public String getComentarios() {
        return (String) getAttributeInternal(COMENTARIOS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comentarios.
     * @param value value to set the Comentarios
     */
    public void setComentarios(String value) {
        setAttributeInternal(COMENTARIOS, value);
    }

    /**
     * Gets the attribute value for DiasParaRespuesta, using the alias name DiasParaRespuesta.
     * @return the value of DiasParaRespuesta
     */
    public Number getDiasParaRespuesta() {
        return (Number) getAttributeInternal(DIASPARARESPUESTA);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiasParaRespuesta.
     * @param value value to set the DiasParaRespuesta
     */
    public void setDiasParaRespuesta(Number value) {
        setAttributeInternal(DIASPARARESPUESTA, value);
    }

    /**
     * Gets the attribute value for FechaVencimiento, using the alias name FechaVencimiento.
     * @return the value of FechaVencimiento
     */
    public Date getFechaVencimiento() {
        return (Date) getAttributeInternal(FECHAVENCIMIENTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaVencimiento.
     * @param value value to set the FechaVencimiento
     */
    public void setFechaVencimiento(Date value) {
        setAttributeInternal(FECHAVENCIMIENTO, value);
    }

    /**
     * Gets the attribute value for NombreSerie, using the alias name NombreSerie.
     * @return the value of NombreSerie
     */
    public String getNombreSerie() {
        return (String) getAttributeInternal(NOMBRESERIE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NombreSerie.
     * @param value value to set the NombreSerie
     */
    public void setNombreSerie(String value) {
        setAttributeInternal(NOMBRESERIE, value);
    }

    /**
     * Gets the attribute value for NombreSubserie, using the alias name NombreSubserie.
     * @return the value of NombreSubserie
     */
    public String getNombreSubserie() {
        return (String) getAttributeInternal(NOMBRESUBSERIE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NombreSubserie.
     * @param value value to set the NombreSubserie
     */
    public void setNombreSubserie(String value) {
        setAttributeInternal(NOMBRESUBSERIE, value);
    }

    /**
     * Gets the attribute value for NombreTpDoc, using the alias name NombreTpDoc.
     * @return the value of NombreTpDoc
     */
    public String getNombreTpDoc() {
        return (String) getAttributeInternal(NOMBRETPDOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for NombreTpDoc.
     * @param value value to set the NombreTpDoc
     */
    public void setNombreTpDoc(String value) {
        setAttributeInternal(NOMBRETPDOC, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param idComunicacion key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number idComunicacion) {
        return new Key(new Object[] { idComunicacion });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        
        SequenceImpl seq = new SequenceImpl("SGD_COMUNICACION_SEQ",getDBTransaction());
        Number seqNextVal = seq.getSequenceNumber();
        setIdComunicacion(seqNextVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    public Integer getSequence () {
        PreparedStatement ps = null;
        ResultSet rs = null;               
        String sequence = "SELECT SGD_COMUNICACION_SEQ.nextval from DUAL";
        
        try {
            ps = getDBTransaction().createPreparedStatement(sequence, 1);
            
            rs = ps.executeQuery();
            
            if (rs.next()) {
                return rs.getInt(1);    
            }
            return 0;
        } catch (Exception ex) {
            throw new oracle.jbo.JboException(ex);
        } finally {
            try {
                ps.close();
            } catch (Exception nex) {
            }
            try {
                rs.close();
            } catch (Exception nex) {
            }
        }
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {        
        super.doDML(operation, e);
    }
}

