package co.gov.anm.sgd.bc.model.entities;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 20 15:42:44 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SGDUsuarioImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdUsuario {
            protected Object get(SGDUsuarioImpl obj) {
                return obj.getIdUsuario();
            }

            protected void put(SGDUsuarioImpl obj, Object value) {
                obj.setIdUsuario((String) value);
            }
        }
        ,
        NombreUsuario {
            protected Object get(SGDUsuarioImpl obj) {
                return obj.getNombreUsuario();
            }

            protected void put(SGDUsuarioImpl obj, Object value) {
                obj.setNombreUsuario((String) value);
            }
        }
        ,
        CodigoDependencia {
            protected Object get(SGDUsuarioImpl obj) {
                return obj.getCodigoDependencia();
            }

            protected void put(SGDUsuarioImpl obj, Object value) {
                obj.setCodigoDependencia((Number) value);
            }
        }
        ,
        Email {
            protected Object get(SGDUsuarioImpl obj) {
                return obj.getEmail();
            }

            protected void put(SGDUsuarioImpl obj, Object value) {
                obj.setEmail((String) value);
            }
        }
        ,
        FechaCreacion {
            protected Object get(SGDUsuarioImpl obj) {
                return obj.getFechaCreacion();
            }

            protected void put(SGDUsuarioImpl obj, Object value) {
                obj.setFechaCreacion((Date) value);
            }
        }
        ,
        FechaActualizacion {
            protected Object get(SGDUsuarioImpl obj) {
                return obj.getFechaActualizacion();
            }

            protected void put(SGDUsuarioImpl obj, Object value) {
                obj.setFechaActualizacion((Date) value);
            }
        }
        ,
        UsuarioCreacion {
            protected Object get(SGDUsuarioImpl obj) {
                return obj.getUsuarioCreacion();
            }

            protected void put(SGDUsuarioImpl obj, Object value) {
                obj.setUsuarioCreacion((String) value);
            }
        }
        ,
        UsuarioActualizacion {
            protected Object get(SGDUsuarioImpl obj) {
                return obj.getUsuarioActualizacion();
            }

            protected void put(SGDUsuarioImpl obj, Object value) {
                obj.setUsuarioActualizacion((String) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(SGDUsuarioImpl object);

        protected abstract void put(SGDUsuarioImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDUSUARIO = AttributesEnum.IdUsuario.index();
    public static final int NOMBREUSUARIO = AttributesEnum.NombreUsuario.index();
    public static final int CODIGODEPENDENCIA = AttributesEnum.CodigoDependencia.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int FECHACREACION = AttributesEnum.FechaCreacion.index();
    public static final int FECHAACTUALIZACION = AttributesEnum.FechaActualizacion.index();
    public static final int USUARIOCREACION = AttributesEnum.UsuarioCreacion.index();
    public static final int USUARIOACTUALIZACION = AttributesEnum.UsuarioActualizacion.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SGDUsuarioImpl() {
    }

    /**
     * Gets the attribute value for IdUsuario, using the alias name IdUsuario.
     * @return the value of IdUsuario
     */
    public String getIdUsuario() {
        return (String) getAttributeInternal(IDUSUARIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdUsuario.
     * @param value value to set the IdUsuario
     */
    public void setIdUsuario(String value) {
        setAttributeInternal(IDUSUARIO, value);
    }

    /**
     * Gets the attribute value for NombreUsuario, using the alias name NombreUsuario.
     * @return the value of NombreUsuario
     */
    public String getNombreUsuario() {
        return (String) getAttributeInternal(NOMBREUSUARIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for NombreUsuario.
     * @param value value to set the NombreUsuario
     */
    public void setNombreUsuario(String value) {
        setAttributeInternal(NOMBREUSUARIO, value);
    }

    /**
     * Gets the attribute value for CodigoDependencia, using the alias name CodigoDependencia.
     * @return the value of CodigoDependencia
     */
    public Number getCodigoDependencia() {
        return (Number) getAttributeInternal(CODIGODEPENDENCIA);
    }

    /**
     * Sets <code>value</code> as the attribute value for CodigoDependencia.
     * @param value value to set the CodigoDependencia
     */
    public void setCodigoDependencia(Number value) {
        setAttributeInternal(CODIGODEPENDENCIA, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for FechaCreacion, using the alias name FechaCreacion.
     * @return the value of FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date) getAttributeInternal(FECHACREACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaCreacion.
     * @param value value to set the FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**
     * Gets the attribute value for FechaActualizacion, using the alias name FechaActualizacion.
     * @return the value of FechaActualizacion
     */
    public Date getFechaActualizacion() {
        return (Date) getAttributeInternal(FECHAACTUALIZACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaActualizacion.
     * @param value value to set the FechaActualizacion
     */
    public void setFechaActualizacion(Date value) {
        setAttributeInternal(FECHAACTUALIZACION, value);
    }

    /**
     * Gets the attribute value for UsuarioCreacion, using the alias name UsuarioCreacion.
     * @return the value of UsuarioCreacion
     */
    public String getUsuarioCreacion() {
        return (String) getAttributeInternal(USUARIOCREACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsuarioCreacion.
     * @param value value to set the UsuarioCreacion
     */
    public void setUsuarioCreacion(String value) {
        setAttributeInternal(USUARIOCREACION, value);
    }

    /**
     * Gets the attribute value for UsuarioActualizacion, using the alias name UsuarioActualizacion.
     * @return the value of UsuarioActualizacion
     */
    public String getUsuarioActualizacion() {
        return (String) getAttributeInternal(USUARIOACTUALIZACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsuarioActualizacion.
     * @param value value to set the UsuarioActualizacion
     */
    public void setUsuarioActualizacion(String value) {
        setAttributeInternal(USUARIOACTUALIZACION, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param idUsuario key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number idUsuario) {
        return new Key(new Object[] { idUsuario });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("co.gov.anm.sgd.bc.model.entities.SGDUsuario");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

