package genericsoap;

import co.gov.anm.sgd.exception.WSException;
import co.gov.anm.sgd.integration.location.ServiceLocator;

import com.oracle.ucm.Field;
import com.oracle.ucm.Generic;
import com.oracle.ucm.Service;

import java.util.ArrayList;
import java.util.Collection;

import weblogic.wsee.jws.jaxws.owsm.SecurityPoliciesFeature;

// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c Development Build 12.2.1.1.0.2047
public class GenericSoapPortClient {
    public static void main(String[] args) {
        GenericSoapService genericSoapService = new GenericSoapService();

        // Configure security feature
        SecurityPoliciesFeature securityFeatures =
            new SecurityPoliciesFeature(new String[] { "oracle/wss11_saml_token_with_message_protection_client_policy" });
        GenericSoapPortType genericSoapPortType = genericSoapService.getGenericSoapPort(securityFeatures);
        // Add your code to call the desired methods.


    }

    public void invocarWS() {
        try {
            GenericSoapPortType port = ServiceLocator.getInstance().getGenericUCMPort(null);

            Collection<Field> fieldList = new ArrayList<Field>();

            Field field = new Field();
            field.setName("dDocName");
            field.setValue("ANM-000002");
            fieldList.add(field);

            field = new Field();
            field.setName("RevisionSelectionMethod");
            field.setValue("Latest");
            fieldList.add(field);

            Service.Document document = new Service.Document();
            document.getField().addAll(fieldList);

            Service service = new Service();
            service.setIdcService("GET_FILE");
            service.setDocument(document);

            Generic request = new Generic();
            request.setWebKey("cs");
            request.setService(service);

            Generic response = port.genericSoapOperation(request);

            Service svrResponse = response.getService();
            Service.Document rspdoc = svrResponse.getDocument();

            for (Field fielRsp : rspdoc.getField()) {
                System.out.println("Name: " + fielRsp.getName());
                System.out.println("Value: " + fielRsp.getValue());
            }
        } catch (WSException e) {

            e.printStackTrace();
        }
    }
}
