package co.gov.anm.sgd.bc.model;

import co.gov.anm.sgd.bc.model.entities.SGDComunicacionImpl;
import co.gov.anm.sgd.bc.model.entities.SGDUsuarioImpl;
import co.gov.anm.sgd.bc.model.views.ComVPSCSEQImpl;
import co.gov.anm.sgd.bc.model.views.SGDComunicacionViewImpl;
import co.gov.anm.sgd.bc.model.views.SGDRolesUsuarioViewImpl;
import co.gov.anm.sgd.bc.model.views.SGDRolesUsuarioViewRowImpl;
import co.gov.anm.sgd.bc.model.views.SGDUsuarioRolViewImpl;
import co.gov.anm.sgd.bc.model.views.SGDUsuarioRolViewRowImpl;
import co.gov.anm.sgd.bc.model.views.SGDUsuarioViewImpl;

import java.util.ArrayList;
import java.util.List;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.SequenceImpl;

import org.apache.log4j.Logger;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 26 11:18:19 COT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ComunicacionesAMImpl extends ApplicationModuleImpl {
    
    private static final Logger logger = Logger.getLogger(ComunicacionesAMImpl.class);
    
    /**
     * This is the default constructor (do not remove).
     */
    public ComunicacionesAMImpl() {
    }
    
    public String getNoRadicado (String codDependencia, String tipoComunicacion) {
        ComVPSCSEQImpl impl = getComVPSCSEQ1();
        String currentYear = null;
        
        impl.executeQuery();
        
        if (impl.hasNext()) {
            Row row = impl.next();
            
            currentYear = row.getAttribute("Currentyear").toString();
        }
        
        SequenceImpl seq = new SequenceImpl("SGD_COM_" + codDependencia + "_SEQ", getDBTransaction());
        Number seqNextVal = seq.getSequenceNumber();                 
        
        return currentYear + codDependencia + String.format("%06d", seqNextVal.intValue()) + tipoComunicacion; 
    }
    
    public void createComunicacion (Row row) throws Exception {
        SGDComunicacionViewImpl view = getSGDComunicacionView1();
        view.insertRow(row);
        
        commit();
    }
    
    public void updateComunicacion (Row rowUpdate) throws Exception {
        commit();
    }
    
    public Row findComunicacionByRadicado (String nroRadicado) {
        SGDComunicacionViewImpl view = getSGDComunicacionView1();
        Row row = null;
        
        ViewCriteria vc = view.createViewCriteria();
        
        ViewCriteriaRow vcr = vc.createViewCriteriaRow();
        vcr.setAttribute(SGDComunicacionImpl.NRORADICADO, nroRadicado);
        
        vc.add(vcr);
        
        view.applyViewCriteria(vc);
        view.executeQuery();
        
        if (view.hasNext()){
            row = view.next();
        } 
        
        return row;
    }
    
    public List<Row> getUsuariosByDependenciaRol (Long idRol, Long codigoDependencia) {
        List<Row> listaUsuarios = new ArrayList<Row>();
        
        //busca diferentes roles en una dependencia
        SGDUsuarioRolViewImpl usuarioRol = getSGDUsuarioRolView1();
        ViewCriteria vc = usuarioRol.createViewCriteria();
            
        ViewCriteriaRow vcr = vc.createViewCriteriaRow();
            
        if (codigoDependencia != 0) {
            vcr.setAttribute(SGDUsuarioRolViewRowImpl.CODIGODEPENDENCIA, codigoDependencia);    
        }
            
        vcr.setAttribute(SGDUsuarioRolViewRowImpl.IDROL, idRol);
            
        vc.add(vcr);
            
        usuarioRol.applyViewCriteria(vc);
        usuarioRol.executeQuery();
            
        while (usuarioRol.hasNext()){
            Row row = usuarioRol.next();
                
            listaUsuarios.add(row);
        }                    
        
        return listaUsuarios;
    }
    
    public List<Row> findRolesUsuario (String idUsuario) {
        SGDRolesUsuarioViewImpl view = getSGDRolesUsuarioView1();
        
        ViewCriteria vc = view.createViewCriteria();
        
        ViewCriteriaRow vcr = vc.createViewCriteriaRow();
        vcr.setAttribute(SGDRolesUsuarioViewRowImpl.IDUSUARIO, idUsuario);
        
        vc.add(vcr);
        
        view.applyViewCriteria(vc);
        view.executeQuery();
        
        List<Row> rowSet = new ArrayList<Row>();
        
        while (view.hasNext()){
            Row row = view.next();
            
            rowSet.add(row);
        }        
        
        return rowSet;
    }
    
    public List<Row> getUsuariosByDependencia (String codigoDependencia) {
        SGDUsuarioViewImpl view = getSGDUsuarioView1();
        
        ViewCriteria vc = view.createViewCriteria();
        
        ViewCriteriaRow vcr = vc.createViewCriteriaRow();
        vcr.setAttribute(SGDUsuarioImpl.CODIGODEPENDENCIA, codigoDependencia);
        
        vc.add(vcr);
        
        view.applyViewCriteria(vc);
        view.executeQuery();
        
        List<Row> rowSet = new ArrayList<Row>();
        
        while (view.hasNext()) {
            Row row = view.next();
            
            rowSet.add(row);
        }
        
        return rowSet;
    }
    
    public Row getComunicacionRow () {
        SGDComunicacionViewImpl view = getSGDComunicacionView1();
        return view.createRow();
    }
    
    public Integer getSecuenciaComunicacion () {
        EntityDefImpl defImpl = SGDComunicacionImpl.getDefinitionObject();
        SGDComunicacionImpl comunicacion = (SGDComunicacionImpl) defImpl.createInstance2(getDBTransaction(), null);
        
        return comunicacion.getSequence();
    }
    
    private void commit () throws Exception {
        try {
            getDBTransaction().commit();   
        } catch (Exception e) {
            logger.error("No se puede hacer commit", e); 
            
            getDBTransaction().rollback();
            
            throw new Exception("Error guardando cambios en la BD", e);
        }
    }

    /**
     * Container's getter for ComVPSCSEQ1.
     * @return ComVPSCSEQ1
     */
    public ComVPSCSEQImpl getComVPSCSEQ1() {
        return (ComVPSCSEQImpl) findViewObject("ComVPSCSEQ1");
    }

    /**
     * Container's getter for SGDComunicacionView1.
     * @return SGDComunicacionView1
     */
    public SGDComunicacionViewImpl getSGDComunicacionView1() {
        return (SGDComunicacionViewImpl) findViewObject("SGDComunicacionView1");
    }


    /**
     * Container's getter for SGDUsuarioRolView1.
     * @return SGDUsuarioRolView1
     */
    public SGDUsuarioRolViewImpl getSGDUsuarioRolView1() {
        return (SGDUsuarioRolViewImpl) findViewObject("SGDUsuarioRolView1");
    }


    /**
     * Container's getter for SGDUsuarioView1.
     * @return SGDUsuarioView1
     */
    public SGDUsuarioViewImpl getSGDUsuarioView1() {
        return (SGDUsuarioViewImpl) findViewObject("SGDUsuarioView1");
    }

    /**
     * Container's getter for SGDRolesUsuarioView1.
     * @return SGDRolesUsuarioView1
     */
    public SGDRolesUsuarioViewImpl getSGDRolesUsuarioView1() {
        return (SGDRolesUsuarioViewImpl) findViewObject("SGDRolesUsuarioView1");
    }
}

