
package co.gov.anm.sgd.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebFault(name = "WSException", targetNamespace = "http://service.sgd.anm.gov.co")
public class WSException_Exception extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private WSException faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public WSException_Exception(String message, WSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WSException_Exception(String message, WSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: co.gov.anm.sgd.service.WSException
     */
    public WSException getFaultInfo() {
        return faultInfo;
    }

}
