<?xml version = '1.0' encoding = 'UTF-8'?>
<schema targetNamespace="http://xmlns.oracle.com/bpel/workflow/task" xmlns:tns="http://xmlns.oracle.com/bpel/workflow/task" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ns4="http://xmlns.oracle.com/bpm/bpmobject/SGDComunicaciones/AdjuntoBO" xmlns:ns2="http://xmlns.oracle.com/bpm/bpmobject/SGDComunicaciones/MetadatosBO" xmlns:ns3="http://xmlns.oracle.com/bpm/bpmobject/SGDComunicaciones/TaxonomiaBO" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://xmlns.oracle.com/bpm/bpmobject/SGDComunicaciones/ComunicacionSalidaBO" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/SGDComunicaciones/UsuarioBO">
   <import namespace="http://xmlns.oracle.com/bpm/bpmobject/SGDComunicaciones/UsuarioBO" schemaLocation="../businessCatalog/SGDComunicaciones/UsuarioBO.xsd"/>
   <import namespace="http://xmlns.oracle.com/bpm/bpmobject/SGDComunicaciones/ComunicacionSalidaBO" schemaLocation="../businessCatalog/SGDComunicaciones/ComunicacionSalidaBO.xsd"/>
   <import namespace="http://xmlns.oracle.com/bpm/bpmobject/SGDComunicaciones/MetadatosBO" schemaLocation="../businessCatalog/SGDComunicaciones/MetadatosBO.xsd"/>
   <import namespace="http://xmlns.oracle.com/bpm/bpmobject/SGDComunicaciones/TaxonomiaBO" schemaLocation="../businessCatalog/SGDComunicaciones/TaxonomiaBO.xsd"/>
   <import namespace="http://xmlns.oracle.com/bpm/bpmobject/SGDComunicaciones/AdjuntoBO" schemaLocation="../businessCatalog/SGDComunicaciones/AdjuntoBO.xsd"/>
   <complexType name="AprobarComunicacionHTPayloadType">
      <sequence>
         <element ref="ns0:UsuarioBO"/>
         <element ref="ns1:ComunicacionSalidaBO"/>
         <element ref="ns2:MetadatosBO"/>
         <element ref="ns3:TaxonomiaBO"/>
         <element name="jefeOficinaProductora" type="xsd:string"/>
         <element name="esRespComunicacionEntrada" type="xsd:boolean"/>
         <element name="tipoPQRS" type="xsd:string"/>
         <element ref="ns4:AdjuntoBO"/>
         <element name="instanceId" type="xsd:string"/>
         <element name="asunto" type="xsd:string"/>
         <element name="radicado" type="xsd:string"/>
         <element name="fechaRadicacion" type="xsd:dateTime"/>
      </sequence>
   </complexType>
</schema>
